'use strict';
const DATA_URL='data/merged_outright.json', MANUAL_URL='data/manual_bond_mapping.json', LOCAL_KEY='twBondManualMapping';
const TERMS=[{key:'1Y',label:'1年',min:.5,max:1.5},{key:'2Y',label:'2年',min:1.5,max:2.5},{key:'5Y',label:'5年',min:4,max:6},{key:'7Y',label:'7年',min:6,max:8},{key:'10Y',label:'10年',min:8,max:12},{key:'20Y',label:'20年',min:15,max:25},{key:'30Y',label:'30年',min:25,max:35}];
let merged={metadata:{},dates:{}}, manual={metadata:{},bonds:{}}, selectedDates=[];
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v??'').replace(/[\s_()（）%％/\-]/g,'').toLowerCase();
function normalizeManual(payload){const bonds=payload?.bonds&&typeof payload.bonds==='object'?payload.bonds:{};return {metadata:{description:'人工補充債券主檔，更新程式不得自動覆蓋或刪除',...(payload?.metadata||{})},bonds:Object.fromEntries(Object.entries(bonds).map(([k,v])=>[String(k).trim().toUpperCase(),{...v,bond_code:String(k).trim().toUpperCase()}]))};}
async function loadJson(url,optional=false){const r=await fetch(`${url}?v=${Date.now()}`,{cache:'no-store'});if(!r.ok){if(optional&&r.status===404)return null;throw new Error(`${url} 載入失敗（HTTP ${r.status}）`)}return r.json()}
async function load(){showError('');$('matrixRoot').innerHTML='<div class="loading">正在載入成交資料…</div>';try{const [m,repoManual]=await Promise.all([loadJson(DATA_URL),loadJson(MANUAL_URL,true)]);merged=m;const local=localStorage.getItem(LOCAL_KEY);manual=normalizeManual(local?JSON.parse(local):(repoManual||{}));render()}catch(e){showError(`${e.message}。請確認 index.html、app.js、styles.css 位於 Repo 根目錄，且 data/merged_outright.json 已存在。`);$('matrixRoot').innerHTML=''}}
function showError(msg){$('errorBanner').textContent=msg;$('errorBanner').classList.toggle('hidden',!msg)}
function asDate(v){if(!v)return null;const d=new Date(`${String(v).slice(0,10)}T00:00:00`);return Number.isNaN(d.getTime())?null:d}
function yearsTo(maturity,asOf){const a=asDate(asOf),m=asDate(maturity);return a&&m?Math.round(((m-a)/86400000/365.25)*10)/10:null}
function manualFor(code){code=String(code||'').toUpperCase();return manual.bonds[code]||manual.bonds[code.replace(/R$/,'')]||null}
function recordYears(r){const m=manualFor(r.bond_code);if(m?.maturity_date)return yearsTo(m.maturity_date,merged.metadata?.remaining_years_as_of||new Date().toISOString().slice(0,10));const n=Number(r.latest_remaining_years);return Number.isFinite(n)?n:null}
function termFor(y){return TERMS.find(t=>y>=t.min&&y<t.max)||null}
function displayDate(s){const [y,m,d]=String(s).split('-');return `${y}/${Number(m)}/${Number(d)}`}
function numberValue(v){if(typeof v==='number'&&Number.isFinite(v))return v;if(v==null)return null;const x=Number(String(v).replace(/[%％,]/g,'').trim());return Number.isFinite(x)?x:null}
function flattenEntries(obj,prefix=''){const out=[];for(const [key,value] of Object.entries(obj||{})){const path=prefix?`${prefix}.${key}`:key;if(value&&typeof value==='object'&&!Array.isArray(value))out.push(...flattenEntries(value,path));else out.push([path,value])}return out}
function yieldFrom(r){
  const market=String(r.market||'').toUpperCase();
  const entries=flattenEntries(r).filter(([key,value])=>numberValue(value)!=null&&!/(券號|代號|日期|年期|面額|金額|筆數|數量|價格|百元價|price|volume|amount|count|date|year)/i.test(key));
  const scored=entries.map(([key,value])=>{const k=norm(key),lower=String(key).toLowerCase();let score=0;
    if(/利率|殖利率|yield|rate/.test(lower))score+=60;
    if(/加權平均|weightedaverage|volumeweightedaverage|weightedavg|vwap/.test(k))score+=market==='EBTS'?100:65;
    if(/平均|average|avg/.test(lower))score+=market==='OTC'?90:45;
    if(/成交|trade|transaction/.test(lower))score+=20;
    if(/最高|最低|high|low|差額|spread/.test(lower))score-=120;
    if(/票面|coupon/.test(lower))score-=100;
    return {key,value:numberValue(value),score};
  }).filter(x=>x.score>0).sort((a,b)=>b.score-a.score);
  return scored.length?{value:scored[0].value,field:scored[0].key}:null;
}
function classify(r){const m=manualFor(r.bond_code),type=String(m?.bond_type||r.bond_type||''),issuer=String(m?.issuer_name||r.issuer_name||'未分類發行人'),code=String(r.bond_code||'');if(/公債|政府|國庫/.test(type)||code.startsWith('A'))return {section:'公債',issuer:'中央政府'};return {section:'公司債',issuer};}
function buildIndex(){const index=new Map(),unmapped=new Map();for(const [date,rows] of Object.entries(merged.dates||{})){for(const r of rows||[]){const code=String(r.bond_code||'').toUpperCase();if(!code)continue;const man=manualFor(code),y=recordYears(r),term=termFor(y),mapped=Boolean(term);if(!mapped){const u=unmapped.get(code)||{code,first:date,last:date,count:0,markets:new Set(),name:r.bond_name_master||r.bond_name||''};u.first=date<u.first?date:u.first;u.last=date>u.last?date:u.last;u.count++;u.markets.add(r.market_zh||r.market||'');unmapped.set(code,u);continue}const c=classify(r),key=[c.section,c.issuer,term.key,code,date].join('|');const item=index.get(key)||{section:c.section,issuer:c.issuer,term,code,date,name:man?.bond_name||r.bond_name_master||r.bond_name||'',years:y,maturity:man?.maturity_date||r.maturity_date,manual:Boolean(man),markets:{}};const yv=yieldFrom(r);if(yv){const mk=String(r.market||'').toUpperCase()==='EBTS'?'EBTS':'OTC';(item.markets[mk]??=[]).push({value:yv.value,field:yv.field,record:r})}index.set(key,item)}}return {index,unmapped}}
function render(){const dates=Object.keys(merged.dates||{}).sort().reverse(),limit=$('dayLimit').value;selectedDates=limit==='all'?dates:dates.slice(0,Number(limit));const {index,unmapped}=buildIndex();const query=$('searchInput').value.trim().toLowerCase();const filtered=[...index.values()].filter(x=>selectedDates.includes(x.date)&&(!query||[x.code,x.name,x.issuer].join(' ').toLowerCase().includes(query)));$('updatedAt').textContent=merged.metadata?.updated_at?.replace('T',' ').slice(0,19)||'尚無';$('asOfDate').textContent=merged.metadata?.remaining_years_as_of||'尚無';$('recordCount').textContent=Number(merged.metadata?.record_count||0).toLocaleString();$('unmappedCount').textContent=unmapped.size.toLocaleString();renderMatrices(filtered);renderUnmapped(unmapped);renderMappingTable()}
function renderMatrices(items){const root=$('matrixRoot');if(!selectedDates.length){root.innerHTML='<div class="panel loading">目前沒有成交日期資料</div>';return}const grouped=new Map();for(const x of items){const key=x.section==='公債'?'公債':`公司債｜${x.issuer}`;(grouped.get(key)??grouped.set(key,[]).get(key)).push(x)}const ordered=[...grouped.keys()].sort((a,b)=>a==='公債'?-1:b==='公債'?1:a.localeCompare(b,'zh-Hant'));root.innerHTML=ordered.length?ordered.map(k=>matrixHtml(k,grouped.get(k))).join(''):'<div class="panel loading">所選條件沒有可顯示的成交資料</div>';root.querySelectorAll('[data-detail]').forEach(btn=>btn.addEventListener('click',()=>openDetail(btn.dataset.detail)))}
function matrixHtml(title,items){const byBond=new Map();for(const x of items){const key=`${x.term.key}|${x.code}`;const b=byBond.get(key)||{term:x.term,code:x.code,name:x.name,issuer:x.issuer,years:x.years,manual:x.manual,dates:{}};b.dates[x.date]=x;byBond.set(key,b)}const bonds=[...byBond.values()].sort((a,b)=>TERMS.findIndex(t=>t.key===a.term.key)-TERMS.findIndex(t=>t.key===b.term.key)||a.code.localeCompare(b.code));let rows='';for(const term of TERMS){const termBonds=bonds.filter(b=>b.term.key===term.key);if(!termBonds.length&&$('tradedOnly').checked)continue;const list=termBonds.length?termBonds:[{term,code:'',name:'',dates:{}}];list.forEach((b,i)=>{rows+=`<tr>${i===0?`<th class="term-cell" rowspan="${list.length}">${term.label}<span class="bond-meta">${term.min}–${term.max}Y</span></th>`:''}<td class="bond-cell">${b.code?`<span class="bond-code">${esc(b.code)}</span>${b.manual?'<span class="manual-mark"> ●人工</span>':''}<span class="bond-meta">${esc(b.name||b.issuer||'')}｜${b.years}Y</span>`:'<span class="empty">無成交</span>'}</td>${selectedDates.map(d=>cellHtml(b.dates[d])).join('')}</tr>`})}return `<section class="matrix-section"><div class="matrix-title"><h2>${esc(title)}</h2><span class="pill">${bonds.length} 檔</span></div><div class="matrix-wrap"><table class="yield-table"><thead><tr><th class="term-head">年期</th><th class="bond-head">券號／名稱</th>${selectedDates.map(d=>`<th>${displayDate(d)}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></div></section>`}
function marketAverage(rows){return rows?.length?rows.reduce((s,x)=>s+x.value,0)/rows.length:null}
function cellHtml(x){if(!x)return '<td class="yield-cell empty">-</td>';const e=marketAverage(x.markets.EBTS),o=marketAverage(x.markets.OTC);if(e!=null&&o!=null){const avg=(e+o)/2,id=btoa(unescape(encodeURIComponent([x.section,x.issuer,x.term.key,x.code,x.date].join('|'))));return `<td class="yield-cell"><button class="yield-link" data-detail="${id}">${avg.toFixed(4)}%</button><span class="market-note">雙市場平均</span></td>`}const v=e??o;if(v==null)return '<td class="yield-cell empty">-</td>';return `<td class="yield-cell"><span class="single-yield">${v.toFixed(4)}%</span><span class="market-note">${e!=null?'等殖':'處所'}</span></td>`}
function openDetail(encoded){const key=decodeURIComponent(escape(atob(encoded))),[section,issuer,term,code,date]=key.split('|');const {index}=buildIndex(),x=index.get([section,issuer,term,code,date].join('|'));if(!x)return;$('detailTitle').textContent=`${code}｜${displayDate(date)}｜雙市場成交`;const cards=['EBTS','OTC'].map(m=>{const rows=x.markets[m]||[],avg=marketAverage(rows);return `<article class="detail-card"><h3>${m==='EBTS'?'等殖成交（EBTS）':'處所成交（OTC）'}</h3><div class="detail-grid"><div><span>採用欄位</span><strong>${esc(rows[0]?.field||'-')}</strong></div><div><span>市場數值</span><strong>${avg==null?'-':avg.toFixed(4)+'%'}</strong></div><div><span>成交筆數</span><strong>${rows.length}</strong></div><div><span>最新剩餘年期</span><strong>${x.years}Y</strong></div></div></article>`}).join('');const e=marketAverage(x.markets.EBTS),o=marketAverage(x.markets.OTC);$('detailBody').innerHTML=`${cards}<article class="detail-card"><h3>顯示值計算</h3><p>(${e.toFixed(4)}% + ${o.toFixed(4)}%) ÷ 2 = <strong>${((e+o)/2).toFixed(4)}%</strong></p></article>`;$('detailDialog').showModal()}
function renderUnmapped(map){const q=$('searchInput').value.trim().toLowerCase(),items=[...map.values()].filter(x=>!q||[x.code,x.name].join(' ').toLowerCase().includes(q)).sort((a,b)=>a.code.localeCompare(b.code));$('unmappedList').innerHTML=items.length?items.map(x=>`<div class="unmapped-item"><div><strong>${esc(x.code)}</strong><small>${esc(x.name||'無主檔名稱')}｜${x.count} 筆｜${esc([...x.markets].join('、'))}</small></div><button class="button secondary map-one" data-code="${esc(x.code)}">補 Mapping</button></div>`).join(''):'<p class="empty">目前沒有未 Mapping 券號。</p>';$('unmappedList').querySelectorAll('.map-one').forEach(b=>b.onclick=()=>openMapping(b.dataset.code))}
function openMapping(code=''){if(code)$('mapCode').value=code;$('mappingDialog').showModal();renderMappingTable()}
function saveManual(){manual.metadata.updated_at=new Date().toISOString();localStorage.setItem(LOCAL_KEY,JSON.stringify(manual));render()}
function renderMappingTable(){const rows=Object.values(manual.bonds).sort((a,b)=>a.bond_code.localeCompare(b.bond_code));$('mappingCount').textContent=rows.length;$('mappingTableWrap').innerHTML=rows.length?`<table class="mapping-table"><thead><tr><th>券號</th><th>到期日</th><th>名稱</th><th>發行人</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.bond_code)}</td><td>${esc(r.maturity_date||'')}</td><td>${esc(r.bond_name||'')}</td><td>${esc(r.issuer_name||'')}</td><td><button class="button danger delete-map" data-code="${esc(r.bond_code)}">刪除</button></td></tr>`).join('')}</tbody></table>`:'<p class="empty">尚無人工 Mapping。</p>';$('mappingTableWrap').querySelectorAll('.delete-map').forEach(b=>b.onclick=()=>{delete manual.bonds[b.dataset.code];saveManual()})}
function upsert(code,maturity,extra={}){code=String(code||'').trim().toUpperCase();if(!/^[A-Z0-9]{5,12}$/.test(code))throw new Error(`券號格式錯誤：${code}`);if(!/^\d{4}-\d{2}-\d{2}$/.test(maturity)||!asDate(maturity))throw new Error(`到期日格式錯誤：${maturity}`);manual.bonds[code]={...(manual.bonds[code]||{}),bond_code:code,maturity_date:maturity,...Object.fromEntries(Object.entries(extra).filter(([,v])=>v)) ,record_source:'manual',manual_override:true}}
function download(){const blob=new Blob([JSON.stringify(manual,null,2)+'\n'],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='manual_bond_mapping.json';a.click();URL.revokeObjectURL(a.href)}
$('refreshButton').onclick=load;$('mappingButton').onclick=()=>openMapping();$('openMappingFromList').onclick=()=>openMapping();$('closeMapping').onclick=()=>$('mappingDialog').close();$('dayLimit').onchange=render;$('tradedOnly').onchange=render;$('searchInput').oninput=render;
$('singleMappingForm').onsubmit=e=>{e.preventDefault();try{upsert($('mapCode').value,$('mapMaturity').value,{bond_name:$('mapName').value.trim(),issuer_name:$('mapIssuer').value.trim(),bond_type:$('mapType').value.trim(),note:$('mapNote').value.trim()});e.target.reset();saveManual()}catch(err){alert(err.message)}};
$('applyBatch').onclick=()=>{try{let n=0;for(const line of $('batchMapping').value.split(/\r?\n/)){if(!line.trim())continue;const [code,maturity]=line.trim().split(/[\t,， ]+/);upsert(code,maturity);n++}$('batchMapping').value='';saveManual();alert(`已加入／更新 ${n} 筆 Mapping`)}catch(err){alert(err.message)}};
$('downloadMapping').onclick=download;$('clearLocalMapping').onclick=()=>{localStorage.removeItem(LOCAL_KEY);location.reload()};$('mappingFile').onchange=async e=>{try{manual=normalizeManual(JSON.parse(await e.target.files[0].text()));saveManual()}catch(err){alert(`JSON 匯入失敗：${err.message}`)}};
load();
